version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: bidi_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-bidi_todo}
    volumes:
      - mongodb_data:/data/db
      - ../../database/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - bidi_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.0
    container_name: bidi_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/${MONGO_DATABASE:-bidi_todo}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-dev_password_123}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bidi_network

volumes:
  mongodb_data:

networks:
  bidi_network:
    driver: bridge
